### ISSUE TITLE
The project is dead, please don't post any issues

### ISSUE THREAD

**Issue by Danibrit1159** [Homebrew-Ports/Among-Us-for-the-3ds#2]
![Screenshot_20210418-173034](https://user-images.githubusercontent.com/63423486/115161478-d925a580-a06b-11eb-992e-b232dd07bc2c.jpg)

**Comment by Loganh4005** [comment]
This is not that port, this was the first one, that was the second one. Keep up with the game here! https://discord.gg/yCpj8NkV
